spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/spinoff?useUnicode=true&characterEncoding=utf-8
    username: spinoff
    password: dbpw2579
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  devtools:
    restart:
      enabled: true # 서버 배포시 false
    livereload:
      enabled: true #서버 배포시 false
  thymeleaf:
    cache: false #서버 배포시 true

decorator:
  datasource:
    p6spy:
      enable-logging: true #서버 배포시 false